### ISSUE TITLE
Change color of the 2nd snake

### ISSUE THREAD

**Issue by 23730027NguyenThiYenLinh** [phamngocthaison/snake-game#12]
![Screenshot 2023-12-05 at 10 04 50 AM](https://github.com/phamngocthaison/snake-game/assets/148703077/13b90b49-19b5-435a-a7af-a28035d5e4d0)

**Comment by 23730058-LeNguyenAnhVu** [comment]
<img width="682" alt="image" src="https://github.com/phamngocthaison/snake-game/assets/148681092/604f387b-a5cb-4e46-9248-b51c1b73e8ea">
Done
