### ISSUE TITLE
[UI/UX] Cannot distinguish healthy/ poisoned snake

### ISSUE THREAD

**Issue by phamngocthaison** [phamngocthaison/snake-game#9]
poisoned & healthy snake has the same sprite

![image](https://github.com/phamngocthaison/snake-game/assets/6897655/8c1eaea0-5dbb-487a-8b9b-1047a6bbc1dc)

Should make it easier to understand the gameplay

**Comment by 23730058-LeNguyenAnhVu** [comment]
done
